import type { Household, HouseholdMember } from '@/types/households'

export const mockHouseholds: Household[] = [
  {
    id: 'HH-0001',
    household_number: 'BHS01-2026-0001',
    respondent_name: 'Santos, Maria C.',
    hh_head_name: 'Santos, Juan A.',
    purok: 'Purok 3',
    street_address: '42 Sampaguita St., Salawag',
    nhts_status: 'NHTS-4Ps',
    is_ip: false,
    hh_head_philhealth_member: true,
    hh_head_philhealth_id_number: '01-123456789-0',
    hh_head_philhealth_category: 'Indigent (sponsored)',
    date_of_visit_q1: '2026-01-16',
    date_of_visit_q2: null,
    date_of_visit_q3: null,
    date_of_visit_q4: null,
    status: 'PENDING_VALIDATION',
    return_reason: null,
    updated_at: '2026-01-16T09:12:00Z',
  },
  {
    id: 'HH-0002',
    household_number: 'BHS01-2026-0002',
    respondent_name: 'Reyes, Ana L.',
    hh_head_name: 'Reyes, Pedro L.',
    purok: 'Purok 1',
    street_address: '15 Rizal Ave., Salawag',
    nhts_status: 'Non-NHTS',
    is_ip: true,
    hh_head_philhealth_member: true,
    hh_head_philhealth_id_number: '01-777777777-7',
    hh_head_philhealth_category: 'Informal economy',
    date_of_visit_q1: '2026-01-18',
    date_of_visit_q2: null,
    date_of_visit_q3: null,
    date_of_visit_q4: null,
    status: 'RETURNED',
    return_reason: 'Missing PhilHealth details for adult members aged 21 and above.',
    updated_at: '2026-01-20T11:02:00Z',
  },
  {
    id: 'HH-0003',
    household_number: 'BHS01-2026-0003',
    respondent_name: 'Garcia, Rosa M.',
    hh_head_name: 'Garcia, Rosa M.',
    purok: 'Purok 5',
    street_address: '8 Mabini St., Salitran IV',
    nhts_status: 'NHTS-4Ps',
    is_ip: false,
    hh_head_philhealth_member: false,
    hh_head_philhealth_id_number: null,
    hh_head_philhealth_category: null,
    date_of_visit_q1: '2026-02-03',
    date_of_visit_q2: null,
    date_of_visit_q3: null,
    date_of_visit_q4: null,
    status: 'PENDING_SYNC',
    return_reason: null,
    updated_at: '2026-02-03T14:27:00Z',
  },
]

export const mockHouseholdMembers: HouseholdMember[] = [
  {
    id: 'HHM-0001',
    household_id: 'HH-0001',
    member_name: 'Santos, Juan A.',
    relationship_to_hh_head_code: '1',
    relationship_other: null,
    sex: 'M',
    birthday: '1983-04-18',
    age: 42,
    classification_q1: 'AB',
    classification_q2: 'AB',
    classification_q3: 'AB',
    classification_q4: 'AB',
    remarks: 'PhilHealth enrolled.',
    is_pregnant: false,
    is_postpartum: false,
    is_pwd: false,
  },
  {
    id: 'HHM-0002',
    household_id: 'HH-0001',
    member_name: 'Santos, Maria C.',
    relationship_to_hh_head_code: '2',
    relationship_other: null,
    sex: 'F',
    birthday: '1985-03-10',
    age: 41,
    classification_q1: 'WRA',
    classification_q2: 'WRA',
    classification_q3: 'WRA',
    classification_q4: 'WRA',
    remarks: 'Pregnancy screening done this quarter.',
    is_pregnant: false,
    is_postpartum: false,
    is_pwd: false,
  },
  {
    id: 'HHM-0003',
    household_id: 'HH-0002',
    member_name: 'Reyes, Pedro L.',
    relationship_to_hh_head_code: '1',
    relationship_other: null,
    sex: 'M',
    birthday: '1961-06-29',
    age: 64,
    classification_q1: 'SC',
    classification_q2: 'SC',
    classification_q3: 'SC',
    classification_q4: 'SC',
    remarks: 'Senior citizen benefits verified.',
    is_pregnant: false,
    is_postpartum: false,
    is_pwd: false,
  },
  {
    id: 'HHM-0004',
    household_id: 'HH-0002',
    member_name: 'Reyes, Ana L.',
    relationship_to_hh_head_code: '2',
    relationship_other: null,
    sex: 'F',
    birthday: '1963-01-14',
    age: 63,
    classification_q1: 'SC',
    classification_q2: 'SC',
    classification_q3: 'SC',
    classification_q4: 'SC',
    remarks: 'Requires follow-up for PhilHealth records update.',
    is_pregnant: false,
    is_postpartum: false,
    is_pwd: false,
  },
  {
    id: 'HHM-0005',
    household_id: 'HH-0003',
    member_name: 'Garcia, Rosa M.',
    relationship_to_hh_head_code: '1',
    relationship_other: null,
    sex: 'F',
    birthday: '2001-09-18',
    age: 24,
    classification_q1: 'WRA',
    classification_q2: 'WRA',
    classification_q3: 'WRA',
    classification_q4: 'WRA',
    remarks: 'Household newly profiled this quarter.',
    is_pregnant: false,
    is_postpartum: false,
    is_pwd: false,
  },
]

export function nextHouseholdId(): string {
  const n = mockHouseholds.length + 1
  return `HH-${String(n).padStart(4, '0')}`
}

export function nextHouseholdNumber(): string {
  const n = mockHouseholds.length + 1
  return `BHS01-2026-${String(n).padStart(4, '0')}`
}

export function nextHouseholdMemberId(): string {
  const n = mockHouseholdMembers.length + 1
  return `HHM-${String(n).padStart(4, '0')}`
}
